characters/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^$', views.front),

    url('^accounts/profile/$', views.redirect_after_login),
    url('^accounts/create/$', views.register),

    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/?$', views.show_user),
    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/edit/$', views.edit_user),
    url('^register/$', views.register),
    url('^users/$', views.list_users),
    url('^users/(?P<username>[a-zA-Z0-9\-_ ]+)/?$', views.show_user),

    url('^characters/$', views.list_characters),
    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/characters/$',
        views.list_characters_for_user),
    url('^c(haracter)?/(?P<character_id>\d+)/morphs/$',
        views.list_morphs_for_character),
    url('^m(orph)?/(?P<morph_id>\d+)/descriptions/$',
        views.list_descriptions_for_morph),
    url('^locations/$', views.list_locations),

    url('^character/create/$', views.create_character),
    url('^morph/create/$', views.create_morph),
    url('^description/create/$', views.create_description),
    url('^location/create/$', views.create_location),

    url('^c(haracter)?/(?P<character_id>\d+)/$', views.show_character),
    url('^m(orph)?/(?P<morph_id>\d+)/$', views.show_morph),
    url('^d(escription)?/(?P<description_id>\d+)/$', views.show_description),
    url('^l(ocation)?/(?P<location_id>\d+)/$', views.show_location),

    url('^c(haracter)?/(?P<character_id>\d+)/edit/$', views.edit_character),
    url('^m(orph)?/(?P<morph_id>\d+)/edit/$', views.edit_morph),
    url('^d(escription)?/(?P<description_id>\d+)/edit/$',
        views.edit_description),
    url('^l(ocation)?/(?P<location_id>\d+)/edit/$', views.edit_location),

    url('^c(haracter)?/(?P<character_id>\d+)/delete/$',
        views.delete_character),
    url('^m(orph)?/(?P<morph_id>\d+)/delete/$', views.delete_morph),
    url('^d(escription)?/(?P<description_id>\d+)/delete/$',
        views.delete_description),
    url('^l(ocation)?/(?P<location_id>\d+)/delete/$', views.delete_location),

    url('^l(ocation)?/(?P<location_id>\d+)/attach/$',
        views.attach_character_to_location),
    url('^location/(?P<characterlocation_id>\d+)/detach/$',
        views.detach_character_from_location),

    url('^species/$', views.list_species),
    url('^species/(?P<species_id>\d+)/$', views.show_species),

    url('^_species/$', views.species_dropdown),
    url('^ajax/list_species/$', views.ajax_list_species),
    url('^ajax/list_genders/$', views.ajax_list_genders),
]

charref/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url('^', include('characters.urls')),
    url('^', include('gallery.urls')),
    url('^', include('django.contrib.auth.urls')),
    url('^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

characters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from gallery.models import ImageAttachment
from activitystream.models import StreamItem


class Character(models.Model):
    name = models.CharField(max_length=60)
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/character/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Morph(models.Model):
    user = models.ForeignKey(User)
    character = models.ForeignKey('Character')
    gender = models.CharField(max_length=20)
    species_text = models.CharField(max_length=60)
    species_category = models.ForeignKey(
        'SpeciesCategory', null=True, blank=True)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return "%s %s (~%s)" % (
            self.gender, self.species_text, self.user.username)

    def get_name(self):
        return "%s %s" % (self.gender, self.species_text)

    def get_absolute_url(self):
        return "/morph/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Description(models.Model):
    RATINGS = (
        ('G', "General"),
        ('M', "Mature"),
        ('R', "Adult")
    )

    # Keeps us from having to say description.morph.character.user
    user = models.ForeignKey(User)
    morph = models.ForeignKey('Morph')
    name = models.CharField(max_length=30)
    description = models.TextField()
    rating = models.CharField(max_length=1, choices=RATINGS)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return "%s (~%s)" % (self.name, self.user.username)

    def get_absolute_url(self):
        return "/description/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Location(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/location/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class CharacterLocation(models.Model):
    character = models.ForeignKey(Character)
    location = models.ForeignKey(Location)
    name_at_location = models.CharField(max_length=50, blank=True)


class SpeciesCategory(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('SpeciesCategory', blank=True, null=True)

    def __unicode__(self):
        if self.parent is None:
            return self.name
        else:
            return "%s (%s)" % (self.name, self.parent.name)

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Species categories"

core/models.py
# from django.db import models

# Create your models here.

gallery/models.py
import os
import time
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import (
    GenericForeignKey,
    GenericRelation,
)
from activitystream.models import StreamItem


def image_path(instance, filename):
    # Whyyyy is this applied twice.  ?.?
    return filename if filename.startswith('gallery/') else os.path.join(
        'gallery',
        str(int(time.time())) + '-' + filename)


class Image(models.Model):
    RATINGS = (
        ('G', "General"),
        ('M', "Mature"),
        ('R', "Adult")
    )

    image = models.ImageField(upload_to=image_path)
    thumbnail = models.ImageField(upload_to='gallery/thumbs', blank=True)
    attribution = models.CharField(max_length=200)
    rating = models.CharField(max_length=1, choices=RATINGS)
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    attachments = GenericRelation(
        'ImageAttachment',
        related_name="generic_image")

    def get_absolute_url(self):
        return "/image/%d" % self.id

    def save(self):
        from PIL import Image as img
        from django.core.files.base import ContentFile
        from StringIO import StringIO

        super(Image, self).save()
        try:
            i = img.open(self.image.path)

            if i.mode not in ('L', 'RGB'):
                i = i.convert('RGB')

            t = i.copy()
            t.thumbnail((128, 128), img.ANTIALIAS)
            fp = StringIO()
            t.save(fp, "JPEG", quality=95)

            self.thumbnail.save(
                name=self.image.name,
                content=ContentFile(
                    fp.getvalue()),
                save=False)

            size = i.size
            if (size[0] > 800 or size[1] > 800):
                r = i.copy()
                r.thumbnail((800, 800), img.ANTIALIAS)
                fp = StringIO()
                r.save(fp, "JPEG", quality=95)

                self.image.save(
                    name=self.image.name,
                    content=ContentFile(
                        fp.getvalue()),
                    save=False)
        except IOError:
            pass

        super(Image, self).save()


class ImageAttachment(models.Model):
    image = models.ForeignKey('Image')
    caption = models.CharField(max_length=200, blank=True)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

characters/forms.py
from django import forms
from django.contrib.auth.models import User
from characters.models import (
    Character,
    Description,
    Location,
    Morph,
)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        exclude = ('user',)


class MorphForm(forms.ModelForm):
    class Meta:
        model = Morph
        exclude = ('user',)
        widgets = {
            'character': forms.HiddenInput()
        }


class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        exclude = ('user',)
        widgets = {
            'morph': forms.HiddenInput(),
            'description': forms.Textarea(attrs={'rows': 10, 'cols': 60})
        }


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        exclude = ('owner',)

core/views.py
# from django.shortcuts import render

# Create your views here.

core/templates/characters/user/edit.html
{% extends "base.html" %}

{% block title %}Edit user - {% endblock %}

{% block header %}Edit user{% endblock %}

{% block content %}
<div id="twoway">
    {% if user == user_object %}
        <div id="updateform">
            {% for error in form.errors %}
                {{ error }}
            {% endfor %}
            <form method="post" action="/~{{ user.username }}/edit/">
                {% csrf_token %}
                <table>
                    <tr>
                        <th><label for="firstname">First name:</label></th>
                        <td><input type="text" name="first_name" value="{{ user.first_name }}" /></td>
                    </tr>
                    <tr>
                        <th><label for="firstname">Last name:</label></th>
                        <td><input type="text" name="last_name" value="{{ user.last_name }}" /></td>
                    </tr>
                    <tr>
                        <th><label for="firstname">E-mail:</label></th>
                        <td><input type="text" name="email" value="{{ user.email }}" /></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="Save" /></td>
                    </tr>
                </table>
            </form>
            <a href="/accounts/password/change/">Change password</a>
        </div>
    {% endif %}
</div>
{% endblock %}

core/templates/characters/user/list.html
{% extends "base.html" %}

{% block title %}Users - {% endblock %}

{% block header %}Users{% endblock %}

{% block content %}
<div id="twoway">
    <div class="plist">
        <ul>
            {% for user in users.object_list %}
            <li class="{% cycle "odd" "even" %}"><a href="/~{{ user.username }}">~{{ user.username }}</a> - {{ user.character_set.count }} characters, {{ user.morph_set.count }} morphs, {{ user.description_set.count }} descriptions, {{ user.image_set.count }} images, {{ user.location_set.count }} locations.</li>
            {% endfor %}
        </ul>
        <hr />
        <div class="pagination">
            <strong>Page:</strong><br />
            {% ifnotequal users.number 1 %}{% ifnotequal users.number 2 %}<a href="?page=1">1</a> ... {% endifnotequal %}{% endifnotequal %}
            {% if users.has_previous %}
            <a href="?page={{ users.previous_page_number }}">{{ users.previous_page_number }}</a>
            {% endif %}

            <strong>{{ users.number }}</strong>

            {% if users.has_next %}
            <a href="?page={{ users.next_page_number }}">{{ users.next_page_number }}</a>
            {% endif %}
            {% ifnotequal users.paginator.num_pages users.number %}{% ifnotequal users.number users.paginator.num_pages|add:"-1" %} ... <a href="?page={{ users.paginator.num_pages }}">{{ users.paginator.num_pages }}</a>{% endifnotequal %}{% endifnotequal %}
        </div>
    </div>
</div>
{% endblock %}

core/templates/characters/user/show.html
{% extends "base.html" %}

{% block head %}
<link rev="canonical" type="text/html" href="http://c.o-f.co/~{{ user_object.username }}" />
{% endblock %}

{% block title %}{{ user_object.username }} (user) - {% endblock %}

{% block header %}~{% if not user_object.is_active %}<s>{% endif %}{{ user_object.username }}{% if not user_object.is_active %}</s>{% endif %}{% endblock %}

{% block content %}
<div id="twoway">
    <div class="wrapper">
        <h3>Stats</h3>
        <p><strong>Username:</strong> {% if not user_object.is_active %}<s>{% endif %}{{ user_object.username }}{% if not user_object.is_active %}</s>{% endif %}
            {% if user_object.is_superuser %}<em>Superuser!</em>{% else %}{% if user_object.is_staff %}<em>Staff!</em>{% endif %}{% endif %}
        </p>
        <p><strong>Name:</strong> {{ user_object.get_full_name }}</p>
        <p><strong>User since:</strong> {{ user_object.date_joined|date:"SHORT_DATE_FORMAT" }}
        <p><strong>Characters:</strong> {{ user_object.character_set.count }}
        <p><strong>Morphs:</strong> {{ user_object.morph_set.count }}
        <p><strong>Descriptions:</strong> {{ user_object.description_set.count }}
        <p>
            <strong>Images:</strong> {{ user_object.image_set.count }} (<a href="/~{{ user_object.username }}/images">list</a>)
            {% if user == user_object %}
            <a href="/image/create/">+ Add image</a>
            {% endif %}
        </p>
        <p><strong>Locations (as owner):</strong> {{ user_object.location_set.count }}
        {% if user == user_object %}
            <hr />
            <p class="addLink"><a href="javascript:void(0)" onclick="$('#updateform').toggle()">Edit info</a></p>
            <div id="updateform" style="display: none">
                {% for error in form.errors %}
                    {{ error }}
                {% endfor %}
                <form method="post" action="/~{{ user.username }}/edit/">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th><label for="firstname">First name:</label></th>
                            <td><input type="text" name="first_name" value="{{ user.first_name }}" /></td>
                        </tr>
                        <tr>
                            <th><label for="firstname">Last name:</label></th>
                            <td><input type="text" name="last_name" value="{{ user.last_name }}" /></td>
                        </tr>
                        <tr>
                            <th><label for="firstname">E-mail:</label></th>
                            <td><input type="text" name="email" value="{{ user.email }}" /></td>
                        </tr>
                        <tr>
                            <td colspan="2"><input type="submit" value="Save" /></td>
                        </tr>
                    </table>
                </form>
                <a href="/accounts/password/change/">Change password</a>
            </div>
        {% endif %}
        <div class="small">Permalink: <a href="http://c.o-f.co{{ request.get_full_path }}">http://c.o-f.co{{ request.get_full_path }}</a></div>
    </div>
    <div class="wrapper">
        <h3>Characters</h3>
        {% for character in user_object.character_set.all %}
        <p><a href="{{ character.get_absolute_url }}">{{ character.name }}</a>
        {% if user_object == user %}
        - <a href="{{character.get_absolute_url }}/delete/">[X]</a></p>
        {% endif %}
        {% endfor %}
        {% if user == user_object %}
            <p class="addLink"><a href="javascript:void(0)" onclick="$('#addCharacter').toggle()">+ Add Character</a></p>
            <form method="post" action="/character/create/" id="addCharacter" style="display: none">
                {% csrf_token %}
                <table>
                    <tr>
                        <th><label for="name">Character name:</label></th>
                        <td><input type="text" name="name" /></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="Create character" /></td>
                    </tr>
                </table>
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}