characters/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^$', views.front),

    url('^accounts/profile/$', views.redirect_after_login),
    url('^accounts/create/$', views.register),

    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/?$', views.show_user),
    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/edit/$', views.edit_user),
    url('^register/$', views.register),
    url('^users/$', views.list_users),
    url('^users/(?P<username>[a-zA-Z0-9\-_ ]+)/?$', views.show_user),

    url('^characters/$', views.list_characters),
    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/characters/$',
        views.list_characters_for_user),
    url('^c(haracter)?/(?P<character_id>\d+)/morphs/$',
        views.list_morphs_for_character),
    url('^m(orph)?/(?P<morph_id>\d+)/descriptions/$',
        views.list_descriptions_for_morph),
    url('^locations/$', views.list_locations),

    url('^character/create/$', views.create_character),
    url('^morph/create/$', views.create_morph),
    url('^description/create/$', views.create_description),
    url('^location/create/$', views.create_location),

    url('^c(haracter)?/(?P<character_id>\d+)/$', views.show_character),
    url('^m(orph)?/(?P<morph_id>\d+)/$', views.show_morph),
    url('^d(escription)?/(?P<description_id>\d+)/$', views.show_description),
    url('^l(ocation)?/(?P<location_id>\d+)/$', views.show_location),

    url('^c(haracter)?/(?P<character_id>\d+)/edit/$', views.edit_character),
    url('^m(orph)?/(?P<morph_id>\d+)/edit/$', views.edit_morph),
    url('^d(escription)?/(?P<description_id>\d+)/edit/$',
        views.edit_description),
    url('^l(ocation)?/(?P<location_id>\d+)/edit/$', views.edit_location),

    url('^c(haracter)?/(?P<character_id>\d+)/delete/$',
        views.delete_character),
    url('^m(orph)?/(?P<morph_id>\d+)/delete/$', views.delete_morph),
    url('^d(escription)?/(?P<description_id>\d+)/delete/$',
        views.delete_description),
    url('^l(ocation)?/(?P<location_id>\d+)/delete/$', views.delete_location),

    url('^l(ocation)?/(?P<location_id>\d+)/attach/$',
        views.attach_character_to_location),
    url('^location/(?P<characterlocation_id>\d+)/detach/$',
        views.detach_character_from_location),

    url('^species/$', views.list_species),
    url('^species/(?P<species_id>\d+)/$', views.show_species),

    url('^_species/$', views.species_dropdown),
    url('^ajax/list_species/$', views.ajax_list_species),
    url('^ajax/list_genders/$', views.ajax_list_genders),
]

charref/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url('^', include('characters.urls')),
    url('^', include('gallery.urls')),
    url('^', include('django.contrib.auth.urls')),
    url('^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

activitystream/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


class StreamItem(models.Model):
    TYPES = (
            ('C', 'created'),
            ('R', 'viewed'),
            ('U', 'edited'),
            ('D', 'deleted'),
            ('IA', 'attached an image to'),
            ('ID', 'detached an image from'),
            ('MA', 'added a morph to'),
            ('MD', 'removed a morph from'),
            ('DA', 'added a description to'),
            ('DD', 'removed a description from'),
            ('LA', 'attached a character to'),
            ('LD', 'detached a character from')
    )

    action_time = models.DateTimeField(auto_now_add=True)
    action_type = models.CharField(max_length=2, choices=TYPES)
    user = models.ForeignKey(User)
    notes = models.TextField(blank=True)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        ordering = ['-action_time']

characters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from gallery.models import ImageAttachment
from activitystream.models import StreamItem


class Character(models.Model):
    name = models.CharField(max_length=60)
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/character/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Morph(models.Model):
    user = models.ForeignKey(User)
    character = models.ForeignKey('Character')
    gender = models.CharField(max_length=20)
    species_text = models.CharField(max_length=60)
    species_category = models.ForeignKey(
        'SpeciesCategory', null=True, blank=True)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return "%s %s (~%s)" % (
            self.gender, self.species_text, self.user.username)

    def get_name(self):
        return "%s %s" % (self.gender, self.species_text)

    def get_absolute_url(self):
        return "/morph/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Description(models.Model):
    RATINGS = (
        ('G', "General"),
        ('M', "Mature"),
        ('R', "Adult")
    )

    # Keeps us from having to say description.morph.character.user
    user = models.ForeignKey(User)
    morph = models.ForeignKey('Morph')
    name = models.CharField(max_length=30)
    description = models.TextField()
    rating = models.CharField(max_length=1, choices=RATINGS)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return "%s (~%s)" % (self.name, self.user.username)

    def get_absolute_url(self):
        return "/description/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Location(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/location/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class CharacterLocation(models.Model):
    character = models.ForeignKey(Character)
    location = models.ForeignKey(Location)
    name_at_location = models.CharField(max_length=50, blank=True)


class SpeciesCategory(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('SpeciesCategory', blank=True, null=True)

    def __unicode__(self):
        if self.parent is None:
            return self.name
        else:
            return "%s (%s)" % (self.name, self.parent.name)

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Species categories"

core/models.py
# from django.db import models

# Create your models here.

characters/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.core.paginator import (
    Paginator,
    EmptyPage,
    InvalidPage,
)
from characters.models import (
    Character,
    Morph,
    Description,
    Location,
    CharacterLocation,
    SpeciesCategory,
)
from gallery.models import Image
from characters.forms import (
    UserForm,
    MorphForm,
    DescriptionForm,
    LocationForm,
)
from activitystream.models import StreamItem


def front(request):
    import random
    counts = {
        'users': User.objects.count(),
        'locations': Location.objects.count(),
        'characters': Character.objects.count(),
        'morphs': Morph.objects.count(),
        'descriptions': Description.objects.count(),
        'images': Image.objects.count()
    }
    new_user = User.objects.order_by('-date_joined')[0]
    random_morph = Morph.objects.all()[
        random.randint(0, Morph.objects.count() - 1)]
    if (request.GET.get('ajax', None) is not None or request.is_ajax()):
        import json
        return HttpResponse(
            json.dumps(
                {
                    'counts': counts,
                    'new_user': new_user.username,
                    'random_morph': {
                        'user': random_morph.user.username,
                        'character': {
                            'id': random_morph.character.id,
                            'name': random_morph.character.name},
                        'morph': {
                            'id': random_morph.id,
                            'display': "%s %s" % (
                                random_morph.gender,
                                random_morph.species_text)}}}),
            mimetype="application/json")
    else:
        return render(
            request, 'front.html',
            {'counts': counts, 'new_user': new_user,
             'random_morph': random_morph})


def redirect_after_login(request):
    return HttpResponseRedirect('/~%s' % request.user.username)


def list_users(request):
    query = User.objects.order_by('username')
    paginator = Paginator(query, 10)

    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        users = paginator.page(page)
    except (EmptyPage, InvalidPage):
        users = paginator.page(paginator.num_pages)

    if (request.is_ajax() or request.GET.get('ajax', None) == 'true'):
        return HttpResponse(
            serializers.serialize(
                "json",
                [users]),
            mimetype="application/json")
    else:
        return render(request, 'characters/user/list.html', {'users': users})


def show_user(request, username):
    user = get_object_or_404(User, username=username)
    if (request.is_ajax() or request.GET.get('ajax', None) == 'true'):
        import json
        return HttpResponse(
            json.dumps(
                {
                    'fields': {
                        'username': user.username,
                        'name': user.get_full_name(),
                        'date_joined': user.date_joined.strftime("%m/%d/%Y"),
                        'is_active': user.is_active,
                        'is_staff': user.is_staff,
                        'is_superuser': user.is_superuser,
                        'email': user.email},
                    'characters': [
                        {
                            'name': i.name,
                            'id': i.id} for i in user.character_set.all()],
                    'morphs': user.morph_set.count(),
                    'descriptions': user.description_set.count(),
                    'images': user.image_set.count(),
                    'locations': user.location_set.count(),
                    'is_owner': request.user == user}),
            mimetype="application/json")
    else:
        return render(request,
                      'characters/user/show.html',
                      {'user_object': user})


@login_required
def edit_user(request, username):
    if (request.user.username != username):
        messages.add_message(
            request, messages.ERROR,
            '<div class="error">You may only edit yourself!</div>')
        return render(request, 'permission_denied.html', {})
    form = UserForm(instance=request.user)
    if (request.method == 'POST'):
        form = UserForm(request.POST, instance=request.user)
        if (form.is_valid()):
            form.save()
            si = StreamItem(
                action_type='U',
                user=request.user,
                content_type=ContentType.objects.get_for_model(User),
                object_id=request.user.id)
            si.save()
            return HttpResponseRedirect("/~%s" % request.user.username)
    return render(request, "characters/user/edit.html",
                  {'form': form, 'user_object': request.user})


def register(request):
    if request.method == 'POST':
        if request.POST.get(
            'username',
            None) and request.POST.get(
            'password',
            None) and request.POST.get(
            'email',
                None):
            user = User.objects.create_user(
                request.POST['username'], request.POST['email'], None)
            user.set_password(request.POST['password'])
            user.save()
            user = User.objects.get(username=request.POST['username'])
            si = StreamItem(
                action_type='C',
                user=user,
                content_type=ContentType.objects.get_for_model(User),
                object_id=user.id)
            si.save()
            return HttpResponseRedirect("/~%s" % user.username)
        else:
            messages.add_message(
                request, messages.WARNING,
                '<div class="failure">Oops!  All fields required!</div>')
    return render(request, "registration/create_user.html", {})

##


def list_characters(request):
    query = Character.objects.all()
    paginator = Paginator(query, 10)

    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        characters = paginator.page(page)
    except (EmptyPage, InvalidPage):
        characters = paginator.page(paginator.num_pages)

    if (request.is_ajax() or request.GET.get('ajax', None) == 'true'):
        return HttpResponse(
            serializers.serialize(
                "json",
                characters),
            mimetype="application/json")
    else:
        return render(request,
                      'characters/character/list.html',
                      {'characters': characters})


def list_characters_for_user(request, username):
    characters = Character.objects.filter(user__username__exact=username)
    if (request.is_ajax() or request.GET.get('ajax', None) == 'true'):
        return HttpResponse(
            serializers.serialize(
                "json",
                characters),
            mimetype="application/json")
    else:
        # Shouldn't ever really happen, this is mostly here for AJAX requests
        return render(request,
                      'characters/character/list.html',
                      {'characters': characters})


def show_character(request, character_id):
    character = get_object_or_404(Character, id=character_id)
    if (request.is_ajax() or request.GET.get('ajax', None) == 'true'):
        import json
        return HttpResponse(json.dumps({
            'fields': {
                'id': character.id,
                'name': character.name,
                'user': character.user.username,
            },
            'morphs': [{
                'id': i.id,
                'name': "%s %s" % (i.gender, i.species_text)
            } for i in character.morph_set.all()],
            'images': [{
                'id': i.id,
                'image_id': i.image.id,
                'thumbnail': i.image.thumbnail.url,
                'attribution': i.image.attribution,
                'rating': i.image.rating,
                'caption': i.caption
            } for i in character.images.all()],
            'is_owner': request.user == character.user,
            'content_type_id': character.get_content_type().id
        }), mimetype="application/json")
    else:
        return render(
            request, 'characters/character/show.html',
            {'character': character,
             'species_select': _species_select_dropdown()})


@login_required
def edit_character(request, character_id):
    c = get_object_or_404(Character, id=character_id)
    if (request.method == "POST"):
        if (request.POST.get('name', None) is not None):
            c.name = request.POST['name']
            c.save()
            si = StreamItem(
                action_type='U',
                user=request.user,
                content_type=ContentType.objects.get_for_model(Character),
                object_id=character_id)
            si.save()
            return HttpResponseRedirect(c.get_absolute_url())
        else:
            messages.add_message(
                request, messages.ERROR,
                '<div class="error">You must enter a name!</div>')
    return render(request, 'characters/character/edit.html', {'character': c})


@login_required
def delete_character(request, character_id):
    character = get_object_or_404(Character, id=character_id)
    if (request.user != character.user):
        # TODO StreamItem flagging user for attempting to delete a character
        # not theirs
        messages.add_message(
            request, messages.ERROR,
            '<div class="error">You may only delete your own '

core/views.py
# from django.shortcuts import render

# Create your views here.

core/templates/characters/morph/delete.html
{% extends "base.html" %}

{% block title %}Delete: {{ morph.gender }} {{ morph.species_text }} (morph) - {% endblock %}

{% block header %}Delete morph: {{ morph.gender }} {{ morph.species_text }} from {{ morph.character.name }}{% endblock %}

{% block content %}
<div id="twoway">
    <div class="wrapper">
        <h3>Confirm!</h3>
        <p>Please make sure you really want to delete this morph!  This action cannot be undone, and will delete descriptions attached to that character!  Images will be detached, but remain uploaded - you can delete them separately.</p>
    </div>
    <div class="wrapper">
        <h3>I agree</h3>
        <p>I understand that this will delete my morph and all descriptions associated with it.</p>
        <form method="post">
            {% csrf_token %}
            <p><input type="checkbox" name="confirm" /> <label for="confirm"><strong>I agree</strong></label></p>
            <p><input type="submit" value="Delete morph" /></p>
        </form>
    </div>
</div>
{% endblock %}

core/templates/characters/morph/edit.html
{% extends "base.html" %}

{% block title %}Edit Morph - {% endblock %}

{% block header %}Edit Morph{% endblock %}

{% block content %}
<div class="wrapper">
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form.hidden_fields %}
        {{ field }}
        {% endfor %}
        <table>
            <tr>
                <th><label for="id_gender">Gender</label></th>
                <td>{{ form.gender }}</td>
                <td>{{ form.gender.errors }}</td>
            </tr>
            <tr>
                <th><label for="species_category">Species category</label></th>
                <td>{{ species_category|safe }}</td>
                <td>{{ form.species_category.errors }}</td>
            </tr>
            <tr>
                <th><label for="id_species_text">Species text</label></th>
                <td>{{ form.species_text }}</td>
                <td>{{ form.species_category.errors }}</td>
            </tr>
            <tr>
                <td colspan="3" style="text-align: center"><input type="submit" value="Save Morph" /></td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

core/templates/characters/morph/show.html
{% extends "base.html" %}

{% block head %}
<link rev="canonical" type="text/html" href="http://c.o-f.co/m/{{ morph.id }}" />
<script type="text/javascript">
    $(function () {
        $('#imageBay').dialog({
            autoOpen: false,
            width: 300,
            height: 400,
            modal: true
        });
        $('#createDescription').dialog({
            autoOpen: false,
            width: 600,
            height: 400,
            modal: true
        });
    });
</script>
{% endblock %}

{% block title %}{{ morph.gender }} {{ morph.species_text }} (morph) - {% endblock %}

{% block header %}<a href="/~{{ morph.user.username }}">~{{ morph.user.username }}</a> / <a href="{{ morph.character.get_absolute_url }}">{{ morph.character.name }}</a> / {{ morph.gender }} {{ morph.species_text }}{% endblock %}

{% block content %}
<div id="twoway">
    <div class="wrapper">
        <h3>Stats</h3>
        <p><strong>Morph gender:</strong> {{ morph.gender }}</p>
        <p><strong>Morph species text:</strong> {{ morph.species_text }}</p>
        <p><strong>Morph species category:</strong> {{ morph.species_category }}</p>
        <p><strong>Morph owner:</strong> <a href="/~{{ morph.user.username }}">{{ morph.user.username }}</a></p>
        {% if morph.user == user %}
        <p class="addLink"><a href="{{ morph.get_absolute_url }}/edit">Edit this morph</a></p>
        <p class="addLink"><a href="javascript:void(0)" onclick="$('#imageBay').dialog('open');">Attach image</a></p>
        {% endif %}
        <!--<div class="astream">
            <h3>Activity stream</h3>
            <ul>
                {% for si in morph.stream_items.all %}
                <li class="{% cycle "odd" "even" %}" title="{{ si.action_time|date:"DATETIME_FORMAT" }}"><a href="/~{{ si.user.username }}">~{{ si.user.username }}</a> {{ si.get_action_type_display }} {{ morph.gender }} {{ morph.species_text }} (morph)</li>
                {% endfor %}
            </ul>
        </div>-->
        <div class="small">Permalink: <a href="http://c.o-f.co/m/{{ morph.id }}">http://c.o-f.co/m/{{ morph.id }}</a></div>
    </div>
    <div class="wrapper">
        <h3>Descriptions</h3>
        {% for description in morph.description_set.all %}
        <p><a href="{{ description.get_absolute_url }}">{{ description.name }}</a> ({{ description.get_rating_display }})
        {% if morph.user == user %}
        - <a href="{{ description.get_absolute_url }}/delete">[X]</a></p>
        {% endif %}
        {% endfor %}
        {% if user == morph.user %}
            <hr />
            <p class="addLink"><a href="javascript:void(0)" onclick="$('#createDescription').dialog('open')">+ Add description</a></p>
            <div id="createDescription" title="Create description">
                <form method="post" action="/description/create/">
                    {% csrf_token %}
                    <input type="hidden" name="morph" value="{{ morph.id }}" />
                    <table>
                        <tr>
                            <th><label for="name">Name:</label></th>
                            <td><input type="text" name="name" /></td>
                        </tr>
                        <tr>
                            <th><label for="description">Description:</label></th>
                            <td><textarea rows="10" cols="50" name="description"></textarea></td>
                        </tr>
                        <tr>
                            <th><label for="rating">Rating:</label></th>
                            <td>
                                <select name="rating">
                                    <option value="G">General</option>
                                    <option value="M">Mature</option>
                                    <option value="R">Adult</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"><input type="submit" value="Create description" /></td>
                        </tr>
                    </table>
                </form>
            </div>
        {% endif %}
    </div>
    <div style="clear: left">
        <h3>Images</h3>
        {% for image in morph.images.all %}
        {% cycle "<div class=\"wrapper\">" "" %}
        <div class="wrapper" style="height: 200px;{% if forloop.counter0|divisibleby:"4" %} clear: left;{% endif %}">
            <a href="{{ image.image.get_absolute_url }}"><img class="thumb{{ image.image.rating }}" src="/media/{{ image.image.thumbnail }}" alt="{{ image.image.attribution }}" /></a><br />
            {{ image.caption }}
            {% if morph.user == user %}
            <a href="/image/{{ image.id }}/detach/">[X]</a>
            {% endif %}
        </div>
        {% cycle "" "</div>" %}
        {% if forloop.last and not forloop.counter|divisibleby:"2" %}
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}