characters/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^$', views.front),

    url('^accounts/profile/$', views.redirect_after_login),
    url('^accounts/create/$', views.register),

    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/?$', views.show_user),
    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/edit/$', views.edit_user),
    url('^register/$', views.register),
    url('^users/$', views.list_users),
    url('^users/(?P<username>[a-zA-Z0-9\-_ ]+)/?$', views.show_user),

    url('^characters/$', views.list_characters),
    url('^~(?P<username>[a-zA-Z0-9\-_ ]+)/characters/$',
        views.list_characters_for_user),
    url('^c(haracter)?/(?P<character_id>\d+)/morphs/$',
        views.list_morphs_for_character),
    url('^m(orph)?/(?P<morph_id>\d+)/descriptions/$',
        views.list_descriptions_for_morph),
    url('^locations/$', views.list_locations),

    url('^character/create/$', views.create_character),
    url('^morph/create/$', views.create_morph),
    url('^description/create/$', views.create_description),
    url('^location/create/$', views.create_location),

    url('^c(haracter)?/(?P<character_id>\d+)/$', views.show_character),
    url('^m(orph)?/(?P<morph_id>\d+)/$', views.show_morph),
    url('^d(escription)?/(?P<description_id>\d+)/$', views.show_description),
    url('^l(ocation)?/(?P<location_id>\d+)/$', views.show_location),

    url('^c(haracter)?/(?P<character_id>\d+)/edit/$', views.edit_character),
    url('^m(orph)?/(?P<morph_id>\d+)/edit/$', views.edit_morph),
    url('^d(escription)?/(?P<description_id>\d+)/edit/$',
        views.edit_description),
    url('^l(ocation)?/(?P<location_id>\d+)/edit/$', views.edit_location),

    url('^c(haracter)?/(?P<character_id>\d+)/delete/$',
        views.delete_character),
    url('^m(orph)?/(?P<morph_id>\d+)/delete/$', views.delete_morph),
    url('^d(escription)?/(?P<description_id>\d+)/delete/$',
        views.delete_description),
    url('^l(ocation)?/(?P<location_id>\d+)/delete/$', views.delete_location),

    url('^l(ocation)?/(?P<location_id>\d+)/attach/$',
        views.attach_character_to_location),
    url('^location/(?P<characterlocation_id>\d+)/detach/$',
        views.detach_character_from_location),

    url('^species/$', views.list_species),
    url('^species/(?P<species_id>\d+)/$', views.show_species),

    url('^_species/$', views.species_dropdown),
    url('^ajax/list_species/$', views.ajax_list_species),
    url('^ajax/list_genders/$', views.ajax_list_genders),
]

charref/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    url,
)
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url('^', include('characters.urls')),
    url('^', include('gallery.urls')),
    url('^', include('django.contrib.auth.urls')),
    url('^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

activitystream/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


class StreamItem(models.Model):
    TYPES = (
            ('C', 'created'),
            ('R', 'viewed'),
            ('U', 'edited'),
            ('D', 'deleted'),
            ('IA', 'attached an image to'),
            ('ID', 'detached an image from'),
            ('MA', 'added a morph to'),
            ('MD', 'removed a morph from'),
            ('DA', 'added a description to'),
            ('DD', 'removed a description from'),
            ('LA', 'attached a character to'),
            ('LD', 'detached a character from')
    )

    action_time = models.DateTimeField(auto_now_add=True)
    action_type = models.CharField(max_length=2, choices=TYPES)
    user = models.ForeignKey(User)
    notes = models.TextField(blank=True)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        ordering = ['-action_time']

characters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from gallery.models import ImageAttachment
from activitystream.models import StreamItem


class Character(models.Model):
    name = models.CharField(max_length=60)
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/character/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Morph(models.Model):
    user = models.ForeignKey(User)
    character = models.ForeignKey('Character')
    gender = models.CharField(max_length=20)
    species_text = models.CharField(max_length=60)
    species_category = models.ForeignKey(
        'SpeciesCategory', null=True, blank=True)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return "%s %s (~%s)" % (
            self.gender, self.species_text, self.user.username)

    def get_name(self):
        return "%s %s" % (self.gender, self.species_text)

    def get_absolute_url(self):
        return "/morph/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Description(models.Model):
    RATINGS = (
        ('G', "General"),
        ('M', "Mature"),
        ('R', "Adult")
    )

    # Keeps us from having to say description.morph.character.user
    user = models.ForeignKey(User)
    morph = models.ForeignKey('Morph')
    name = models.CharField(max_length=30)
    description = models.TextField()
    rating = models.CharField(max_length=1, choices=RATINGS)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return "%s (~%s)" % (self.name, self.user.username)

    def get_absolute_url(self):
        return "/description/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class Location(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    images = GenericRelation(ImageAttachment)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/location/%d" % self.id

    def get_content_type(self):
        return ContentType.objects.get_for_model(self)


class CharacterLocation(models.Model):
    character = models.ForeignKey(Character)
    location = models.ForeignKey(Location)
    name_at_location = models.CharField(max_length=50, blank=True)


class SpeciesCategory(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('SpeciesCategory', blank=True, null=True)

    def __unicode__(self):
        if self.parent is None:
            return self.name
        else:
            return "%s (%s)" % (self.name, self.parent.name)

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Species categories"

core/models.py
# from django.db import models

# Create your models here.

gallery/models.py
import os
import time
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import (
    GenericForeignKey,
    GenericRelation,
)
from activitystream.models import StreamItem


def image_path(instance, filename):
    # Whyyyy is this applied twice.  ?.?
    return filename if filename.startswith('gallery/') else os.path.join(
        'gallery',
        str(int(time.time())) + '-' + filename)


class Image(models.Model):
    RATINGS = (
        ('G', "General"),
        ('M', "Mature"),
        ('R', "Adult")
    )

    image = models.ImageField(upload_to=image_path)
    thumbnail = models.ImageField(upload_to='gallery/thumbs', blank=True)
    attribution = models.CharField(max_length=200)
    rating = models.CharField(max_length=1, choices=RATINGS)
    user = models.ForeignKey(User)
    stream_items = GenericRelation(StreamItem)
    attachments = GenericRelation(
        'ImageAttachment',
        related_name="generic_image")

    def get_absolute_url(self):
        return "/image/%d" % self.id

    def save(self):
        from PIL import Image as img
        from django.core.files.base import ContentFile
        from StringIO import StringIO

        super(Image, self).save()
        try:
            i = img.open(self.image.path)

            if i.mode not in ('L', 'RGB'):
                i = i.convert('RGB')

            t = i.copy()
            t.thumbnail((128, 128), img.ANTIALIAS)
            fp = StringIO()
            t.save(fp, "JPEG", quality=95)

            self.thumbnail.save(
                name=self.image.name,
                content=ContentFile(
                    fp.getvalue()),
                save=False)

            size = i.size
            if (size[0] > 800 or size[1] > 800):
                r = i.copy()
                r.thumbnail((800, 800), img.ANTIALIAS)
                fp = StringIO()
                r.save(fp, "JPEG", quality=95)

                self.image.save(
                    name=self.image.name,
                    content=ContentFile(
                        fp.getvalue()),
                    save=False)
        except IOError:
            pass

        super(Image, self).save()


class ImageAttachment(models.Model):
    image = models.ForeignKey('Image')
    caption = models.CharField(max_length=200, blank=True)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

characters/forms.py
from django import forms
from django.contrib.auth.models import User
from characters.models import (
    Character,
    Description,
    Location,
    Morph,
)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        exclude = ('user',)


class MorphForm(forms.ModelForm):
    class Meta:
        model = Morph
        exclude = ('user',)
        widgets = {
            'character': forms.HiddenInput()
        }


class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        exclude = ('user',)
        widgets = {
            'morph': forms.HiddenInput(),
            'description': forms.Textarea(attrs={'rows': 10, 'cols': 60})
        }


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        exclude = ('owner',)

core/views.py
# from django.shortcuts import render

# Create your views here.

core/templates/characters/location/list.html
{% extends "base.html" %}

{% block title %}Locations - {% endblock %}

{% block header %}Locations{% endblock %}

{% block content %}
<div id="twoway">
    <div class="wrapper">
        <p>Locations are places where your characters might be found.  They can be instant messaging services, chatrooms, MUCKs, forums, etc.  You can attach a character of yours to a location, and give it a name at that location if it differs from the character's name.  This will let people find you around the internet!</p>
        <p>Don't see a location you want?  Let me know, shoot me an email at &lt; makyo @ drab-makyo . com &gt; without spaces!</p>
    </div>
    <div class="wrapper plist">
        <ul>
            {% for location in locations.object_list %}
            <li class="{% cycle "odd" "even" %}"><a href="{{ location.get_absolute_url }}">{{ location.name }}</a> - {{ location.characterlocation_set.count }} characters</li>
            {% endfor %}
        </ul>
        <hr />
        <div class="pagination">
            <strong>Page:</strong><br />
            {% ifnotequal locations.number 1 %}{% ifnotequal locations.number 2 %}<a href="?page=1">1</a> ... {% endifnotequal %}{% endifnotequal %}
            {% if locations.has_previous %}
            <a href="?page={{ locations.previous_page_number }}">{{ locations.previous_page_number }}</a>
            {% endif %}

            <strong>{{ locations.number }}</strong>

            {% if locations.has_next %}
            <a href="?page={{ locations.next_page_number }}">{{ locations.next_page_number }}</a>
            {% endif %}
            {% ifnotequal locations.paginator.num_pages locations.number %}{% ifnotequal locations.number locations.paginator.num_pages|add:"-1" %} ... <a href="?page={{ locations.paginator.num_pages }}">{{ locations.paginator.num_pages }}</a>{% endifnotequal %}{% endifnotequal %}
        </div>
    </div>
</div>
{% endblock %}

core/templates/characters/location/show.html
{% extends "base.html" %}

{% block head %}
<link rev="canonical" type="text/html" href="http://c.o-f.co/l/{{ location.id }}" />
<script type="text/javascript">
    $(function () {
        $('#imageBay').dialog({ 
            autoOpen: false,
            width: 300,
            height: 400,
            modal: true
        });
        $('#attachForm').dialog({ 
            autoOpen: false,
            width: 400,
            height: 200,
            modal: true
        });
    });
</script>
{% endblock %}

{% block title %}{{ location.name }} (location) - {% endblock %}

{% block header %}<a href="/locations">Locations</a> / {{ location.name }}{% endblock %}

{% block content %}
<div id="twoway">
    <div class="wrapper">
        <div>{{ location.description|safe }}</div>
        <p><strong>Owner:</strong> <a href="/~{{ location.user.username }}">~{{ location.user }}</a></p>
        {% if location.user == user %}
        <p><a href="{{ location.get_absolute_url }}/edit">Edit this location</a></p>
        {% endif %}
        <div class="small">Permalink: <a href="http://c.o-f.co/l/{{ location.id }}">http://c.o-f.co/l/{{ location.id }}</a></div>
        <h3>Images</h3>
        {% for image in location.images.all %}
        <div>
            <a href="{{ image.image.get_absolute_url }}"><img src="/media/{{ image.image.thumbnail }}" alt="{{ image.image.attribution }}" /></a><br />
            {{ image.caption }}
            {% if location.user == user %}
            <a href="/image/{{ image.id }}/detach/">[X]</a>
            {% endif %}
        </div>
        {% endfor %}
        <div class="astream">
            <ul>
                {% for si in location.stream_items.all %}
                {% if forloop.counter < 10 %}
                <li class="{% cycle "odd" "even" %}" title="{{ si.action_time|date:"DATETIME_FORMAT" }}"><a href="/~{{ si.user.username }}">~{{ si.user.username }}</a> {{ si.get_action_type_display }} {{ location.name }} (location)</li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="wrapper">
        {% if user.is_authenticated %}
        <a href="javascript:void(0)" onclick="$('#attachForm').dialog('open')">+ Attach a character</a>
        <div id="attachForm" title="Attach a character to this location">
            <form method="get" action="/location/{{ location.id }}/attach">
                <p><strong><label for="character_id">Character:</label></strong> <select name="character_id">
                    {% for character in user.character_set.all %}
                    <option value="{{ character.id }}">{{ character.name }}</option>
                    {% endfor %}
                </select></p>
                <p><strong><label for="as">Name at location (if different):</label></strong> <input type="text" name="as" /></p>
                <input type="submit" value="Attach character" />
            </form>
        </div>
        {% endif %}
        <div class="plist">
            <ul>
                {% for cl in location.characterlocation_set.all %}
                <li class="{% cycle "odd" "even" %}">
                    <a href="{{ cl.character.get_absolute_url }}">{{ cl.character.name }}</a>
                    {% if cl.name_at_location != "" %}
                    <em> as {{ cl.name_at_location }}</em>
                    {% endif %}
                    (<a href="/~{{ cl.character.user.username }}">~{{ cl.character.user.username }}</a>)
                    {% if cl.character.user == user %}
                    <a href="/location/{{ cl.id }}/detach">[X]</a>
                    {% endif %}
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
</div>
{% if location.user == user %}
<div id="imageBay" title="Attach an image">
    {% for image in user.image_set.all %}
    <form method="post" action="/image/{{ image.id }}/attach/">
        {% csrf_token %}
        <input type="hidden" name="content_type" value="{{ location.get_content_type.id }}" />
        <input type="hidden" name="object_id" value=" {{location.id }}" />
        <p><input type="image" src="/media/{{ image.thumbnail }}" alt="Attach image" /></p>
        <p><strong>Caption:</strong> <input type="text" name="caption" /></p>
    </form>
    {% if not forloop.last %}
    <hr />
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endblock %}